# change this to include the packages you need 
channels:
  - conda-forge
  - bioconda
dependencies:
  - openjdk=8.0.152
  - bwa==0.7.17
  - samtools==1.14
  - r-base==4.1.1  
  - r-essentials=4.1
  - r-renv=0.14.0 
  - python=3.6
  - bioconda::tabix==1.11
  - ghostscript==9.54.0
  - snakemake
  - regtools=0.5.0

