# change this to include the packages you need 
channels:
  - conda-forge
  - bioconda
dependencies:
  - openjdk=8.0.152
  - bwa==0.7.17
  - samtools==1.14
  - r-base<4.0.0
  - r-essentials
  - r-rstan
  - r-remotes
  - python=3.6
  - bioconda::tabix==1.11
  - ghostscript==9.54.0
  - snakemake
  - regtools=0.5.0
  - ucsc-gtftogenepred
  - bioconda::r-biocmanager


